import React, { useState } from 'react';
import { PANABO } from './data.js';
import { Btn, Card, CardHeader, CardBody, Badge, Inp } from './components.jsx';

export function ReportsScreen({ role }) {
  const [type, setType]   = useState('Suitability Summary');
  const [parcel, setParcel] = useState('PCL-00184');
  const [filter, setFilter] = useState('');

  const filtered = PANABO.reports.filter(r =>
    !filter || r.type.toLowerCase().includes(filter.toLowerCase()) || r.parcel.toLowerCase().includes(filter.toLowerCase())
  );

  return (
    <div className="page">
      <div className="page-header">
        <div>
          <h1 className="page-title">Reports</h1>
          <p className="page-subtitle">Generate, review, and download land analysis reports</p>
        </div>
        {role === 'admin' && <Btn variant="brand" icon="plus">New Report</Btn>}
      </div>

      <div className="grid grid-3" style={{ marginBottom: 20 }}>
        <div style={{ gridColumn: '1 / 3' }}>
          <Card>
            <CardHeader><span className="card-title">Report Builder</span></CardHeader>
            <CardBody>
              <div className="grid grid-2" style={{ gap: 14, marginBottom: 14 }}>
                <div>
                  <label className="label">Report Type</label>
                  <select className="input" value={type} onChange={e => setType(e.target.value)}>
                    {['Suitability Summary','Environmental Clearance','Zone Compliance Check','Reforestation Plan'].map(t => <option key={t}>{t}</option>)}
                  </select>
                </div>
                <div>
                  <label className="label">Parcel</label>
                  <select className="input" value={parcel} onChange={e => setParcel(e.target.value)}>
                    {PANABO.parcels.map(p => <option key={p.id} value={p.id}>{p.id}</option>)}
                  </select>
                </div>
              </div>
              <div style={{ marginBottom: 14 }}>
                <label className="label">Sections to include</label>
                <div className="row" style={{ gap: 8, flexWrap: 'wrap' }}>
                  {['Executive Summary','MCDA Scores','Zone Compliance','Environmental Flags','Recommendations'].map(s => (
                    <label key={s} className="chip" style={{ cursor: 'pointer' }}>
                      <input type="checkbox" defaultChecked style={{ accentColor: 'hsl(var(--brand))' }}/> {s}
                    </label>
                  ))}
                </div>
              </div>
              <div className="row" style={{ gap: 8 }}>
                <Btn variant="brand" icon="file">Generate Report</Btn>
                <Btn variant="outline" icon="eye">Preview</Btn>
              </div>
            </CardBody>
          </Card>
        </div>

        <Card>
          <CardHeader><span className="card-title">PDF Preview</span></CardHeader>
          <CardBody>
            <div style={{ background: 'hsl(var(--muted))', borderRadius: 8, padding: 14, fontSize: 12.5, lineHeight: 1.7, minHeight: 180 }}>
              <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 6 }}>{type}</div>
              <div className="muted">Parcel: {parcel}</div>
              <div className="muted">Date: {new Date().toLocaleDateString()}</div>
              <div className="muted">Prepared by: CPDO, Panabo City</div>
              <hr className="separator" style={{ margin: '10px 0' }}/>
              <div className="muted" style={{ fontSize: 11.5 }}>
                This report presents the results of the Multi-Criteria Decision Analysis (MCDA) for the selected parcel…
              </div>
            </div>
          </CardBody>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <div className="row-between">
            <span className="card-title">Report Archive</span>
            <Inp icon="search" placeholder="Search reports…" value={filter} onChange={e => setFilter(e.target.value)} style={{ width: 200 }}/>
          </div>
        </CardHeader>
        <div style={{ overflowX: 'auto' }}>
          <table className="table">
            <thead>
              <tr><th>ID</th><th>Type</th><th>Parcel</th><th>Date</th><th>Status</th><th>Generated by</th><th></th></tr>
            </thead>
            <tbody>
              {filtered.map(r => (
                <tr key={r.id}>
                  <td><span className="mono muted" style={{ fontSize: 11.5 }}>{r.id}</span></td>
                  <td>{r.type}</td>
                  <td><span style={{ fontWeight: 500 }}>{r.parcel}</span></td>
                  <td>{r.date}</td>
                  <td><Badge variant={r.status === 'Final' ? 'brand' : r.status === 'Draft' ? 'warn' : r.status === 'Review' ? '' : ''}>{r.status}</Badge></td>
                  <td>{r.generatedBy}</td>
                  <td>
                    <div className="row" style={{ gap: 4 }}>
                      <Btn sz="xs" variant="ghost" icon="eye"/>
                      <Btn sz="xs" variant="ghost" icon="download"/>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
